name: Run Python Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  COBOL_APP_PATH: ${{ github.workspace }}/legacy_cobol_app
  PY_VER: 3.13.7

jobs:
  testing-python-versions:
    runs-on: [self-hosted, ubuntu, x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}

      - name: Setup env variables
        run: |
          export PYENV_ROOT="$HOME/.pyenv"
          echo "PYENV_ROOT=$PYENV_ROOT" >> $GITHUB_ENV
          echo "$PYENV_ROOT/bin:$PATH" >> $GITHUB_PATH

      - name: Install pyenv deps
        run: |
          sudo apt install -y \
          make build-essential libssl-dev zlib1g-dev \
          libbz2-dev libreadline-dev libsqlite3-dev wget curl \
          llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev \
          libffi-dev liblzma-dev python3-openssl git

      - name: Install pyenv
        run: |
          if [ ! -d "$PYENV_ROOT" ]; then
            curl -fsSL https://pyenv.run | bash
          fi

      - name: Install Python
        run: |
          eval "$(pyenv init -)"

          pyenv install -s $PY_VER
          pyenv global $PY_VER
          python --version
          pip --version

      - name: Install Cobol
        run: |
          sudo apt install gnucobol -y

      - name: Compile Cobol Code
        run: |
          cobc -x main.cob operations.cob data.cob -o accountsystem

      - name: Run tests
        run: |
          eval "$(pyenv init -)"
          cd $COBOL_APP_PATH
          python test_cobol_operations.py
